version: '3.8'
services:
  db:
    image: postgres:13
    container_name: manage_gym_postgres
    environment:
      POSTGRES_USER: gym_admin
      POSTGRES_PASSWORD: GymPass123
      POSTGRES_DB: manage_gym_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gym_admin -d manage_gym_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
    container_name: manage_gym_backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://gym_admin:GymPass123@db:5432/manage_gym_db
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]

volumes:
  postgres_data:

